packages/main/src/backend/users.ts
packages/main/src/index.ts
packages/main/src/ipcHandlers/index.ts
packages/main/src/ipcHandlers/userHandlers.ts
packages/preload/src/users.ts
packages/renderer/src/store/Modules/UserState.ts
packages/renderer/vite.config.js
packages/types/User.d.ts
packages/types/index.d.ts

refactor: remove caching code

---

packages/main/src/backend/users.ts

change how user objects are handled in the modifying functions in
backend/users.ts. These are changed from complete object deconstruction
in the parameter list and then almost complete object construction
in the axios calls to the javascript destructering API

refactor: change user backend calls

---

packages/main/src/backend/groups.ts
packages/main/src/backend/operations.ts
packages/main/src/backend/permissions.ts
packages/main/src/backend/users.ts

create better error messages based on the received http status and
the state of the axError

feat(error-handling): better error messages

---

packages/renderer/src/components/BasicComponents/FloatingErrorToast.vue
packages/renderer/src/components/BasicComponents/FormInput.vue
packages/renderer/src/components/BasicComponents/NormalButton.vue
packages/renderer/src/components/LoginForm.vue
packages/renderer/src/views/CreateNewUser.vue
packages/renderer/src/views/LoginPage.vue
packages/renderer/tailwind.config.js
tailwind.config.js

Add additional superlight and superdark color shades, repurpose
surface color for use with e.g. inputs as gray colors and change
styles

refactor: add more color shades and change styles

---

packages/renderer/src/components/SideBarMenu.vue
packages/renderer/src/router/index.ts
packages/renderer/src/store/Modules/UserState.ts
packages/renderer/src/views/AllGroups.vue
packages/renderer/src/views/CreateNewGroup.vue
packages/renderer/src/views/EditGroup.vue
packages/renderer/src/views/MainApplication.vue

feat: add group management ui
style: fix typo in retreiveUser functions

Add group management ui &  fix typo in retreiveUser functions

---

packages/renderer/src/views/AllGroups.vue
packages/renderer/src/views/CreateNewGroup.vue
packages/renderer/src/views/EditGroup.vue

add search input to member model to filter the users which can be
selected using the multiple select

change: add search functionality to member modal

---

packages/renderer/src/views/AllGroups.vue
packages/renderer/src/views/CreateNewGroup.vue
packages/renderer/src/views/EditGroup.vue

fix thrown when server responses take too long in AllGroups.vue,
CreateNewGroup.vue and EditGroup.vue

fix: timing issues with group views

---

packages/main/src/backend/groups.ts
packages/main/src/backend/operations.ts
packages/main/src/backend/users.ts
packages/renderer/src/components/BasicComponents/NormalButton.vue
packages/renderer/src/components/BasicComponents/PaginatedTable.vue
packages/renderer/src/store/Modules/GroupState.ts
packages/renderer/src/store/Modules/OperationsState.ts
packages/renderer/src/store/Modules/UserState.ts
packages/renderer/src/views/AllGroups.vue
packages/renderer/src/views/EditGroup.vue
packages/types/index.d.ts

feat: add paginated table compnent

feat: add paginated table compnent

---

packages/renderer/src/views/AllOperations.vue
packages/renderer/src/views/AllUsers.vue
packages/renderer/src/views/CreateNewUser.vue

Added Pagination for All Users and All Operations View
Fixed a Bug where Form for new User was not alligned

#86 Pagination for Users and Operations

---

src/app/core/model/group.ts
src/app/core/model/operation.ts
src/app/core/model/permissions.ts
src/app/core/services/group.service.spec.ts
src/app/core/services/group.service.ts
src/app/core/services/operation.service.spec.ts
src/app/core/services/operation.service.ts
src/app/core/services/permission.service.ts
src/app/core/services/permissions.service.spec.ts

This adds services and tests for
-operations
-groups
-permissions

Feature Basic Services

---

.github/workflows/angular.yml
angular.json
package.json

ci: add build job for german translation

---

src/app/core/components/quick-search/quick-search.component.html
src/app/core/components/quick-search/quick-search.component.spec.ts
src/app/core/components/searchable-multi-chip-input-field/searchable-multi-chip-entity-input.component.spec.ts
src/app/core/services/group.service.spec.ts
src/app/core/services/group.service.ts
src/app/core/services/operation.service.spec.ts
src/app/core/services/operation.service.ts
src/app/features/management/operation-management-view/operation-management-view.component.html
src/app/features/management/operation-management-view/operation-management-view.component.scss
src/app/features/management/operation-management-view/operation-management-view.component.spec.ts
src/app/features/management/operation-management-view/operation-management-view.component.ts
src/app/features/management/user-management-view/create-user-view/create-user-view.component.spec.ts
src/app/features/management/user-management-view/edit-user-view/edit-user-view.component.spec.ts
src/app/features/management/user-management-view/user-management-view.component.scss
src/locale/messages.de.xlf
src/locale/messages.xlf
src/styles/corporate.scss
src/styles/tables.scss

151 feature add operation list view

---

src/app/core/components/local-paginated-list/local-paginated-list.component.html
src/app/core/components/local-paginated-list/local-paginated-list.component.spec.ts
src/app/core/components/local-paginated-list/local-paginated-list.component.ts
src/app/core/core.module.ts
src/app/core/util/store.ts

Adds a paginated list that uses local data instead of fetching.

refactor(core-components): add local paginated list

---

src/app/core/components/loading-dots/loading-dots.component.html
src/app/core/components/loading-dots/loading-dots.component.scss
src/app/core/components/loading-dots/loading-dots.component.ts
src/app/core/components/loading-overlay/loading-overlay.component.html
src/app/core/components/loading-overlay/loading-overlay.component.ts
src/app/core/core.module.ts
src/app/core/directives/show-loading-dots.directive.ts
src/app/core/directives/show-loading-overlay.directive.ts
src/app/core/util/loader.ts
src/app/features/management/user-management-view/edit-user-view/edit-user-view.component.ts
src/app/features/management/user-management-view/update-user-password-view/update-user-password-view.component.ts
src/styles/global.scss

Extracted from former #154 as it is required in #160.

Fix loading indication issues

---

src/app/core/model/intel.ts
src/app/core/services/intel.service.spec.ts
src/app/core/services/intel.service.ts

Closes [#171](https://github.com/mobile-directing-system/mds-desktop/issues/171).

171-feature-add-intel-service

---

src/app/core/components/searchable-entity-input/searchable-entity-input.component.html
src/app/core/components/searchable-entity-input/searchable-entity-input.component.ts
src/app/features/logistics/address-book-entry-list-view/address-book-entry-list-view.component.html
src/app/features/logistics/address-book-entry-list-view/create-address-book-entry-view/create-address-book-entry-view.component.html
src/app/features/logistics/address-book-entry-list-view/edit-address-book-entry-view/edit-address-book-entry-view.component.html
src/locale/messages.de.xlf
src/locale/messages.xlf

Changed the address book operation selecture feature. If no operation is selected "all" will be shown as selected operation for a better user experience.

change: address book operation - default all for not selected

---

src/app/core/pipes/duration.pipe.spec.ts
src/app/core/pipes/duration.pipe.ts

Fixed [BUG]: Format edit duration displays wrong milliseconds

---

src/app/features/intelligence/create-intel-stepper/create-intel-stepper.component.ts

Set priority simple as default when creating a new intel

[CHANGE]: priority simple as default

---

src/app/core/constants/routes.ts
src/app/features/logistics/logistics-layout/logistics-layout.component.html
src/app/features/logistics/logistics-layout/logistics-layout.component.spec.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

added permission check on route and navigation button. added tests.

fixed [BUG]: Add permission guards for manual intel delivery

---

src/app/features/logistics/channels/channel-details-dialog/channel-details-dialog.component.html
src/locale/messages.de.xlf
src/locale/messages.xlf

Added missing translations for channel details dialog

fixed [BUG]: Missing translations for channel details dialog

---

src/app/core/components/home-layout/home-layout.component.scss
src/app/core/components/key-info-bar/key-info-bar.component.html
src/app/core/components/key-info-bar/key-info-bar.component.scss
src/app/core/components/key-info-bar/key-info-bar.component.spec.ts
src/app/core/components/key-info-bar/key-info-bar.component.ts
src/app/core/components/searchable-multi-chip-input-field/searchable-multi-chip-entity-input.component.html
src/app/core/components/view/view.component.html
src/app/core/components/view/view.component.scss
src/app/core/components/view/view.component.ts
src/app/core/core.module.ts
src/app/core/directives/autofocus.directive.ts
src/app/core/services/intel-creation.service.ts
src/app/core/services/key-info.service.spec.ts
src/app/core/services/key-info.service.ts
src/app/features/intelligence/create-intel-stepper/create-intel-stepper.component.html
src/app/features/intelligence/create-intel-stepper/create-intel-stepper.component.spec.ts
src/app/features/intelligence/create-intel-stepper/create-intel-stepper.component.ts
src/app/features/intelligence/intel-in-creation-side-nav/intel-in-creation-side-nav.component.scss
src/app/features/intelligence/intelligence-layout/intelligence-layout.component.html
src/app/features/intelligence/intelligence-layout/intelligence-layout.component.scss
src/app/features/intelligence/intelligence-layout/intelligence-layout.component.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

177-feature-toolbar-for-autofilling-keys

---

src/app/app.module.ts
src/app/core/model/incident.ts
src/app/core/model/resource.ts
src/app/core/services/addressbook.service.ts
src/app/core/services/local-storage.service.spec.ts
src/app/core/services/resource/local-storage-resource.service.spec.ts
src/app/core/services/resource/local-storage-resource.service.ts
src/app/core/services/resource/resource.service.ts
src/app/core/util/local-storage.ts

Adds a resource service that provides CRUD functionalities and stores data in localStorage

Feature: Resource Service

---

src/app/core/constants/routes.ts
src/app/core/services/resource/local-storage-resource.service.ts
src/app/core/services/resource/resource.service.ts
src/app/core/util/local-storage.ts
src/app/features/logistics/address-book-entry-list-view/edit-address-book-entry-view/edit-address-book-entry-view.component.ts
src/app/features/resources/edit-resource/edit-resource.component.html
src/app/features/resources/edit-resource/edit-resource.component.scss
src/app/features/resources/edit-resource/edit-resource.component.spec.ts
src/app/features/resources/edit-resource/edit-resource.component.ts
src/app/features/resources/list-resources/list-resources.component.html
src/app/features/resources/list-resources/list-resources.component.spec.ts
src/app/features/resources/list-resources/list-resources.component.ts
src/app/features/resources/resources.module.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

Adds a page to edit a resource (#222)

Feature: Edit resources

---

src/app/core/model/resource.ts
src/app/features/resources/edit-resource/edit-resource.component.html
src/app/features/resources/edit-resource/edit-resource.component.ts
src/app/features/resources/list-resources/list-resources.component.html
src/app/features/resources/list-resources/list-resources.component.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

Add feature to edit status of resources
#231

Feature: Edit status of resources

---

src/app/core/core.module.ts
src/app/core/services/incident/incident.service.ts
src/app/core/services/incident/local-storage-incident.service.spec.ts
src/app/core/services/incident/local-storage-incident.service.ts
src/app/features/operation-table/operation-table-view/operation-table-view.component.html
src/app/features/operation-table/operation-table-view/operation-table-view.component.scss
src/app/features/operation-table/operation-table-view/operation-table-view.component.spec.ts
src/app/features/operation-table/operation-table-view/operation-table-view.component.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

Feature: Complete incident

---

src/app/core/model/message.ts
src/app/core/services/message/local-storage-message.service.spec.ts
src/app/core/services/message/local-storage-message.service.ts
src/app/core/services/message/message.service.ts
src/app/core/services/resource/local-storage-resource.service.spec.ts

Feature: Add messages service

---

src/app/app.module.ts
src/app/core/services/resource/local-storage-resource.service.ts
src/app/features/signaler/incoming/signaler-incoming-view.component.html
src/app/features/signaler/incoming/signaler-incoming-view.component.scss
src/locale/messages.de.xlf
src/locale/messages.xlf

* Add missing translations
* Search is now case insensitive
* Register message service for DI
Closes #240

Fix: Bugs on incoming message page

---

src/app/core/components/channel-type-inline/channel-type-inline.component.html
src/app/core/components/channel-type-inline/channel-type-inline.component.spec.ts
src/app/core/services/message/local-storage-message.service.spec.ts
src/app/features/signaler/incoming/signaler-incoming-view.component.html
src/app/features/signaler/incoming/signaler-incoming-view.component.spec.ts
src/app/features/signaler/incoming/signaler-incoming-view.component.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

Feature: Submit incoming messages

---

src/app/core/components/searchable-entity-input/searchable-entity-input.component.ts
src/app/core/components/searchable-multi-chip-input-field/searchable-multi-chip-entity-input.component.ts
src/app/core/constants/routes.ts
src/app/core/services/auth.service.spec.ts
src/app/core/services/auth.service.ts
src/app/core/services/message/local-storage-message.service.spec.ts
src/app/core/services/message/local-storage-message.service.ts
src/app/core/services/message/message.service.ts
src/app/features/mailbox/create-message/create-message.component.html
src/app/features/mailbox/create-message/create-message.component.scss
src/app/features/mailbox/create-message/create-message.component.spec.ts
src/app/features/mailbox/create-message/create-message.component.ts
src/app/features/mailbox/fakedata.json
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.html
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.scss
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.spec.ts
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.ts
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.html
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.scss
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.spec.ts
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.ts
src/app/features/mailbox/mailbox-layout/mailbox-layout.component.html
src/app/features/mailbox/mailbox-layout/mailbox-layout.component.scss
src/app/features/mailbox/mailbox-layout/mailbox-layout.component.spec.ts
src/app/features/mailbox/mailbox-layout/mailbox-layout.component.ts
src/app/features/mailbox/mailbox.module.ts
src/app/features/management/manage-layout/manage-layout.component.html
src/locale/messages.de.xlf
src/locale/messages.xlf

Mailbox for receiving and sending messages. A manager can see incoming messages, mark them as read and answer with new messages.

Feat: Mailbox

---

src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.ts

Fix: Sort by date on mailbox table

---

src/app/core/constants/routes.ts
src/app/features/mailbox/create-message/create-message.component.spec.ts
src/app/features/mailbox/create-message/create-message.component.ts
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.html
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.ts

[FEATURE]: Mailbox - retain context when reacting to a message #249

---

src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.spec.ts
src/app/features/reviewer/outgoing/outgoing-messages-view/outgoing-messages-view.component.html
src/app/features/reviewer/outgoing/outgoing-messages-view/outgoing-messages-view.component.spec.ts
src/app/features/reviewer/outgoing/outgoing-messages-view/outgoing-messages-view.component.ts
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.html
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.scss
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.spec.ts
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.ts
src/app/features/reviewer/reviewer.module.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

Feature: Add dialog for reviewer to select outgoing channels

---

src/app/core/components/importance-inline/importance-inline.component.html
src/app/core/model/importance.ts
src/app/features/logistics/channels/channels.component.spec.ts

change: remove national emergency importance

---

src/app/features/logistics/address-book-entry-list-view/edit-address-book-entry-view/edit-address-book-entry-view.component.html
src/app/features/logistics/address-book-entry-list-view/edit-address-book-entry-view/edit-address-book-entry-view.component.scss
src/app/features/logistics/address-book-entry-list-view/edit-address-book-entry-view/edit-address-book-entry-view.component.ts
src/app/features/logistics/channels/channels.component.html
src/app/features/logistics/channels/channels.component.scss
src/locale/messages.de.xlf
src/locale/messages.xlf

Change: Remove auto intel delivery from address book edit page

---

src/app/core/services/channel.service.spec.ts
src/app/features/logistics/channels/channel-details-dialog/channel-details-dialog.component.html
src/app/features/logistics/channels/channel-details-dialog/channel-details-dialog.component.scss
src/app/features/logistics/channels/channel-details-dialog/channel-details-dialog.component.spec.ts

Change: remove channel form fields that are no longer needed

---

src/app/features/logistics/channels/channels.component.html
src/app/features/logistics/channels/channels.component.spec.ts
src/app/features/logistics/channels/channels.component.ts

Change: Refactor channel table

---

src/app/core/model/channel.ts
src/app/core/services/channel.service.ts

Fix: Create/update phone channel

---

src/app/core/model/channel.ts
src/app/features/logistics/channels/channels.component.html
src/app/features/logistics/channels/channels.component.spec.ts
src/app/features/logistics/channels/channels.component.ts
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.html
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.ts

Fix: Missing channel info on reviewer dialog

---

src/app/features/reviewer/incoming/review-dialog/review-dialog.component.html
src/app/features/reviewer/incoming/review-dialog/review-dialog.component.spec.ts
src/app/features/reviewer/incoming/review-dialog/review-dialog.component.ts

Feature: Add status on reviewer dialog

---

src/app/core/model/message.ts
src/app/core/services/message/local-storage-message.service.spec.ts
src/app/core/services/message/local-storage-message.service.ts
src/app/core/services/message/message.service.ts
src/app/features/mailbox/create-message/create-message.component.spec.ts
src/app/features/mailbox/create-message/create-message.component.ts
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.spec.ts
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.spec.ts
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.ts
src/app/features/reviewer/incoming/incoming-messages-view/incoming-messages-view.component.spec.ts
src/app/features/reviewer/incoming/incoming-messages-view/incoming-messages-view.component.ts
src/app/features/reviewer/incoming/review-dialog/review-dialog.component.spec.ts
src/app/features/reviewer/outgoing/outgoing-messages-view/outgoing-messages-view.component.spec.ts
src/app/features/reviewer/outgoing/outgoing-messages-view/outgoing-messages-view.component.ts
src/app/features/signaler/incoming/signaler-incoming-view.component.spec.ts
src/app/features/signaler/incoming/signaler-incoming-view.component.ts
src/app/features/signaler/outgoing/delivery-item/delivery-item.component.spec.ts
src/app/features/signaler/outgoing/signaler-outgoing-view.component.spec.ts
src/app/features/signaler/outgoing/signaler-outgoing-view.component.ts
src/locale/messages.de.xlf
src/locale/messages.xlf

Feature: Filter messages by operation

---

src/app/core/constants/routes.ts
src/app/features/mailbox/incoming-messages-view/incoming-message/incoming-message.component.html
src/app/features/mailbox/incoming-messages-view/incoming-messages-view.component.html
src/app/features/management/group-management-view/create-group-view/create-group-view.component.html
src/app/features/management/group-management-view/create-group-view/create-group-view.component.ts
src/app/features/management/group-management-view/edit-group-view/edit-group-view.component.html
src/app/features/management/group-management-view/edit-group-view/edit-group-view.component.spec.ts
src/app/features/management/group-management-view/edit-group-view/edit-group-view.component.ts
src/app/features/management/group-management-view/group-management-view.component.html
src/app/features/management/group-management-view/group-management-view.component.spec.ts
src/app/features/management/manage-layout/manage-layout.component.html
src/app/features/management/manage-layout/manage-layout.component.spec.ts
src/app/features/management/user-management-view/edit-user-permissions-view/edit-user-permissions-view.component.html
src/app/features/operation-table/operation-table-view/operation-table-view.component.html
src/locale/messages.de.xlf
src/locale/messages.xlf

Change: Rename groups

---

src/app/core/components/importance-inline/importance-inline.component.html
src/app/core/components/importance-inline/importance-inline.component.scss
src/app/core/model/importance.ts
src/app/core/services/intel-creation.service.spec.ts
src/app/features/intelligence/create-intel-confirmation-dialog/create-intel-confirmation-dialog.component.spec.ts
src/app/features/intelligence/intel-in-creation-side-nav/intel-in-creation-side-nav.component.spec.ts
src/app/features/logistics/intel-delivery/deliver-channel/deliver-channel.component.spec.ts
src/app/features/logistics/intel-delivery/intel-to-deliver-attempts/intel-to-deliver-attempts.component.spec.ts
src/app/features/logistics/intel-delivery/intel-to-deliver-channel-selection/intel-to-deliver-channel-selection.component.spec.ts
src/app/features/logistics/intel-delivery/intel-to-deliver-details/intel-to-deliver-details.component.spec.ts
src/app/features/logistics/intel-delivery/open-intel-deliveries-table/open-intel-deliveries-table.component.spec.ts

Change: Remove priority low

---

src/app/features/signaler/incoming/signaler-incoming-view.component.html

The channel type form will not be resetted anymore.

Fix: Bug when stepper is resetted on signaler page

---

src/app/core/services/message/local-storage-message.service.ts
src/app/features/reviewer/outgoing/outgoing-messages-view/outgoing-messages-view.component.ts
src/app/features/reviewer/outgoing/select-channel-dialog/select-channel-dialog.component.ts
src/app/features/signaler/outgoing/signaler-outgoing-view.component.ts

Make resource channels selectable for the reviewer

Feature: Select resource channels
